### PR TITLE
Small cleanup

### PR DESCRIPTION
**Pull request by 1ma**
I've only deleted a couple of placeholder configuration files and made the bundle compatible with Symfony 3.0 and beyond.

I'd very much appreciate if you could release your bundle at Packagist, maybe as `marcoshoya/masterpass-bundle` or some such.

Thanks!

### CODE REVIEW

**Comment by marcoshoya** [comment]
Thanks dude. I didn't have time to check Symfony 3 improvement.
I will try publishing this bundle as soon as possible at packagist.

Thanks

**Comment by 1ma** [comment]
Cool :+1: 

I've started a more concerted refactoring effort but I've kept it in a separate branch because it is bigger and it _might_ introduce some BC changes.

Feel free to [take a look](https://github.com/1ma/MasterpassBundle/commits/develop) at the commits, I'm keeping them small to ease readability. If you're also interested in these changes I'll submit a second PR.

**Comment by marcoshoya** [comment]
Branch looks good. I agree with your changes although this bundle is not finished yet. Most of those classes needs to be removed and refactored as well because I am taking from oficial SDK.
I am going to try releasing at least an "1.0" version by end of this week.

Thanks

**Comment by 1ma** [comment]
I know. In fact, just a couple of days ago I was considering doing _exactly_ what you've done here, but then I poked the internet a little and found this repo. And since it saved me a lot of time I felt like giving something back.

I totally agree that the official SDK should be completely redesigned but I, for one, don't have the time nor the inclination to do the MasterPass' developers job for free. As you might have seen my "bigger refactor" just removes dead code, fixes most PHPDoc annotations and irons out some of the ugliest warts, like the `com_create_guid()` call.

Even though most of these are rather simple changes they touch almost every file in the codebase, that's why I decided to keep them in a separate branch in case it was too much to take at once. But since you are OK with this I'll submit a second PR after you merge this one. I'd appreciate to have them both in the 1.0 release.

Cheers :beer:

**Comment by marcoshoya** [comment]
Absolutely. Please, open a new pull request and I can merge all stuff. Tomorrow I am going to work on this bundle all day long.

Regards

**Pull request closed without merging**
